### ISSUE TITLE
Отсутствие возможности собрать в разных режимах

### ISSUE THREAD

**Issue by alexmikhalevich** [Mrkol/hw_strategygame#15]
В требованиях написано:

> при вызове cmake && make должен собираться ваш проект в режиме Release
> при вызове cmake -DDEBUG=ON && make должен собираться ваш проект в режиме Debug
> при вызове cmake -DWITH_TEST=ON && make должен собираться ваш проект с тестами

не нашел этой возможности.

**Comment by Mrkol** [comment]
Такая возможность есть. CMakeLists.txt корневой директории реагирует на эти флаги. Если имелось в виду что-либо бо́льшее, пожалуйста, уточните.

**Comment by alexmikhalevich** [comment]
И правда, странно. Возможно, issue случайно попало к вам в репозиторий :)
