### ISSUE TITLE
Чистота кода

### ISSUE THREAD

**Issue by alexmikhalevich** [Mrkol/hw_strategygame#17]
Избыточное копирование. https://github.com/Mrkol/hw_strategygame/blob/4379d80cc1f73f167efe539a1c41ff6f5ff4758d/common/include/EntityTypeBuilder.hpp#L20

**Comment by Mrkol** [comment]
Исправлено в ветке development. Будет влито в мастер как только замечаний по первому чекпоинту не останется.
